//
// Created by Øystein Bringsli on 12/11/2023.
//

#ifndef PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_MYKEYLISTENER_HPP
#define PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_MYKEYLISTENER_HPP


class MyKeyListener {
};


#endif//PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_MYKEYLISTENER_HPP
