//
// Created by Øystein Bringsli on 10/3/2023.
//

#ifndef PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_VEC2_HPP
#define PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_VEC2_HPP


class Vec2 {
};


#endif//PROSJEKTOPPGAVE_OYSTEIN_BRINGSLI_VEC2_HPP
